AWSTemplateFormatVersion: 2010-09-09

Description: Template to create an EC2 instance and enable SSH

Parameters: 
  KeyName:
    Description: Name of SSH KeyPair
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Provide the name of an existing SSH key pair


Resources:
  MyB24EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-098bb3651924ae737
      KeyName: !Ref KeyName
      PrivateIpAddress: 172.31.55.98
      SecurityGroups:
       - Ref: InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: My CF Instance
      
      UserData:
        Fn::Base64: |
          #!/bin/bash
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

          yum install -y sendmail
          
          echo '; Configure error processing
                display_errors = On
                error_reporting = E_ALL & ~E_NOTICE & ~E_WARNING

                ; Set some more PHP parameters
                enable_dl = Off
                short_open_tag = On
                allow_url_fopen = On

                ; Change default values of important constants
                max_input_vars = 10000
                max_file_uploads = 100
                max_execution_time = 300
                post_max_size = 1024M
                upload_max_filesize = 1024M
                pcre.backtrack_limit = 1000000
                pcre.recursion_limit = 14000
                realpath_cache_size = 4096k
                mysql.default_socket = /var/lib/mysqld/mysqld.sock
                mysqli.default_socket = /var/lib/mysqld/mysqld.sock

                ; Utf-8 support
                mbstring.func_overload = 2
                default_charset = UTF-8

                ; Configure PHP sessions
                session.entropy_length = 128
                session.entropy_file = /dev/urandom
                session.save_path = "/tmp/php_sessions/www"
                session.cookie_httponly = On

                ; Set directory for temporary files
                upload_tmp_dir = "/tmp/php_upload/www"

                sendmail_path="/usr/sbin/sendmail -t -i -f your@email.ru"
                date.timezone = Europe/Moscow
                memory_limit = 256M' > /etc/php.d/z_bx_custom_settings.ini

          echo 'root:$6$ftfiXw9l$.UL3DVGs9fyxIi5eATwzSVjD9IYd4uUldWVJjfE6ED2jUTzVxS9G3e9Y24mf8kZJDnInjkWXVp9LR58JahiUp0:18390:0:99999:7:::
              bin:*:17834:0:99999:7:::
              daemon:*:17834:0:99999:7:::
              adm:*:17834:0:99999:7:::
              lp:*:17834:0:99999:7:::
              sync:*:17834:0:99999:7:::
              shutdown:*:17834:0:99999:7:::
              halt:*:17834:0:99999:7:::
              mail:*:17834:0:99999:7:::
              operator:*:17834:0:99999:7:::
              games:*:17834:0:99999:7:::
              ftp:*:17834:0:99999:7:::
              nobody:*:17834:0:99999:7:::
              systemd-network:!!:18225::::::
              dbus:!!:18225::::::
              polkitd:!!:18225::::::
              sshd:!!:18225::::::
              postfix:!!:18225::::::
              chrony:!!:18225::::::
              bitrix:$6$V9vHno0P$taX8jkKw4lSjZ5l.foLaXPSG/oxQeGqDSo3pIA6Y5TCSWWfRneky7AaOMrw1a6Wzt6DA5CAF7wkx3UribnROm.:18390:0:99999:7:::
              mysql:!!:18225::::::
              apache:!!:18225::::::
              munin:!!:18225::::::
              tss:!!:18225::::::
              ntp:!!:18225::::::
              nginx:!!:18225::::::
              gluster:!!:18225::::::
              saslauth:!!:18390::::::
              mailnull:!!:18390::::::
              smmsp:!!:18390::::::' > /etc/shadow

          echo 'root:x:0:0:root:/root:/bin/bash
              bin:x:1:1:bin:/bin:/sbin/nologin
              daemon:x:2:2:daemon:/sbin:/sbin/nologin
              adm:x:3:4:adm:/var/adm:/sbin/nologin
              lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
              sync:x:5:0:sync:/sbin:/bin/sync
              shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
              halt:x:7:0:halt:/sbin:/sbin/halt
              mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
              operator:x:11:0:operator:/root:/sbin/nologin
              games:x:12:100:games:/usr/games:/sbin/nologin
              ftp:x:14:50:FTP User:/var/ftp:/sbin/nologin
              nobody:x:99:99:Nobody:/:/sbin/nologin
              systemd-network:x:192:192:systemd Network Management:/:/sbin/nologin
              dbus:x:81:81:System message bus:/:/sbin/nologin
              polkitd:x:999:998:User for polkitd:/:/sbin/nologin
              sshd:x:74:74:Privilege-separated SSH:/var/empty/sshd:/sbin/nologin
              postfix:x:89:89::/var/spool/postfix:/sbin/nologin
              chrony:x:998:996::/var/lib/chrony:/sbin/nologin
              bitrix:x:600:600::/home/bitrix:/bin/bash
              mysql:x:27:27:Percona Server:/var/lib/mysql:/bin/false
              apache:x:48:48:Apache:/usr/share/httpd:/sbin/nologin
              munin:x:599:599:Munin user:/var/lib/munin:/bin/sh
              tss:x:59:59:Account used by the trousers package to sandbox the tcsd daemon:/dev/null:/sbin/nologin
              ntp:x:38:38::/etc/ntp:/sbin/nologin
              nginx:x:598:598:nginx user:/var/cache/nginx:/sbin/nologin
              gluster:x:597:597:GlusterFS daemons:/run/gluster:/sbin/nologin
              saslauth:x:596:76:Saslauthd user:/run/saslauthd:/sbin/nologin
              mailnull:x:47:47::/var/spool/mqueue:/sbin/nologin
              smmsp:x:51:51::/var/spool/mqueue:/sbin/nologin' > /etc/passwd

          exec > >(tee /var/log/user-data-pool.log|logger -t user-data -s 2>/dev/console) 2>&1
                
          echo -e "1\n\n\n0" > /opt/webdir/bin/cp.txt
          /opt/webdir/bin/pool_menu.sh < /opt/webdir/bin/cp.txt

          exec > >(tee /var/log/user-data-pp.log|logger -t user-data -s 2>/dev/console) 2>&1

          echo -e "ip-172-31-55-98.ec2.internal\nY\n\n0\n0" > /opt/webdir/bin/menu/10_push/pp.txt
          /opt/webdir/bin/menu/10_push/01_configure_push_service.sh < /opt/webdir/bin/menu/10_push/pp.txt

    
    
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable access via port 22 and 80 and 443
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0




Outputs: 
  InstanceID:
    Description: The Instance ID
    Value: !Ref MyB24EC2Instance
