AWSTemplateFormatVersion: 2010-09-09

Description: Template to create an EC2 instance and enable SSH

Parameters: 
  KeyName:
    Description: Name of SSH KeyPair
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Provide the name of an existing SSH key pair


Resources:
  MyB24EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-098bb3651924ae737
      KeyName: !Ref KeyName
      SecurityGroups:
       - Ref: InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: My CF Instance
      
      UserData:
        Fn::Base64: |
          #!/bin/bash
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
          yum update -y
          yum install -y sendmail
          echo '; Configure error processing\n
                display_errors = On\n
                error_reporting = E_ALL & ~E_NOTICE & ~E_WARNING\n

                ; Set some more PHP parameters\n
                enable_dl = Off\n
                short_open_tag = On\n
                allow_url_fopen = On\n

                ; Change default values of important constants\n
                max_input_vars = 10000\n
                max_file_uploads = 100\n
                max_execution_time = 300\n
                post_max_size = 1024M\n
                upload_max_filesize = 1024M\n
                pcre.backtrack_limit = 1000000\n
                pcre.recursion_limit = 14000\n
                realpath_cache_size = 4096k\n
                mysql.default_socket = /var/lib/mysqld/mysqld.sock\n
                mysqli.default_socket = /var/lib/mysqld/mysqld.sock\n

                ; Utf-8 support\n
                mbstring.func_overload = 2\n
                default_charset = UTF-8\n

                ; Configure PHP sessions\n
                session.entropy_length = 128\n
                session.entropy_file = /dev/urandom\n
                session.save_path = "/tmp/php_sessions/www"\n
                session.cookie_httponly = On\n

                ; Set directory for temporary files\n
                upload_tmp_dir = "/tmp/php_upload/www"\n

                sendmail_path="/usr/sbin/sendmail -t -i -f y@bedrosova.ru"\n
                date.timezone = Europe/Moscow\n
                memory_limit = 256M' > /etc/php.d/z_bx_custom_settings.ini
    
    
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable access via port 22 and 80 and 443
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0




Outputs: 
  InstanceID:
    Description: The Instance ID
    Value: !Ref MyB24EC2Instance
