AWSTemplateFormatVersion: 2010-09-09

Description: Template to create an EC2 instance and enable SSH

Parameters: 
  KeyName:
    Description: Name of SSH KeyPair
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Provide the name of an existing SSH key pair


Resources:
  MyB24EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-098bb3651924ae737
      KeyName: !Ref KeyName
      SecurityGroups:
       - Ref: InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: My CF Instance
      
      UserData:
        Fn::Base64: |
          #!/bin/bash
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
          yum update -y
          yum install -y sendmail
    
    Metadata:
      'AWS::CloudFormation::Init':
        files:
          /etc/php.d/bitrixenv.ini:
            content: !Sub | 
              ; Set parameters required for proper Bitrix engine functioning.
              ; You can redefine parameters specified in this file
              ; by editing /etc/php.d/z_bx_custom_settings.ini

              ; Configure error processing
              display_errors = On
              error_reporting = E_ALL & ~E_NOTICE & ~E_WARNING

              ; Set some more PHP parameters
              enable_dl = Off
              short_open_tag = On
              allow_url_fopen = On

              ; Change default values of important constants
              max_input_vars = 10000
              max_file_uploads = 100
              max_execution_time = 300
              post_max_size = 1024M
              upload_max_filesize = 1024M
              pcre.backtrack_limit = 1000000
              pcre.recursion_limit = 14000
              realpath_cache_size = 4096k
              mysql.default_socket = /var/lib/mysqld/mysqld.sock
              mysqli.default_socket = /var/lib/mysqld/mysqld.sock

              ; Utf-8 support
              mbstring.func_overload = 2
              default_charset = UTF-8

              ; Configure PHP sessions
              session.entropy_length = 128
              session.entropy_file = /dev/urandom
              session.save_path = "/tmp/php_sessions/www"
              session.cookie_httponly = On

              ; Set directory for temporary files
              upload_tmp_dir = "/tmp/php_upload/www"

              sendmail_path="/usr/sbin/sendmail -t -i -f y@bedrosova.ru"
              date.timezone = Europe/Moscow
              memory_limit = 256M
      
            mode: "000644"
            owner: "root"
            group: "root"

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable access via port 22 and 80 and 443
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0



  
Outputs: 
  InstanceID:
    Description: The Instance ID
    Value: !Ref MyB24EC2Instance
